#!/bin/bash
DATE=`date +"%Y-%M-%d-%H-%m-%S"`
ZIPFILE="customer_store_credit_${DATE}.zip"
MAILRECEIPENTS="as-support@intelligrape.com,tech@taslc.com"
#MAILRECEIPENTS="navjots@intelligrape.com"
php customer_store_credit.php > /tmp/customer_store_credit_report_${DATE}.csv
cd /tmp && zip $ZIPFILE /customer_store_credit_report_${DATE}.csv
scp -i /home/ubuntu/.ssh/Utility.pem /tmp/${ZIPFILE} ubuntu@10.0.0.109:/tmp/
ssh  -i /home/ubuntu/.ssh/Utility.pem ubuntu@10.0.0.109 sudo aws s3 cp /tmp/${ZIPFILE}  s3://qa-americanswan/dump/
echo -e "Hi Team,\n\nPlease download report generated by customer_store_credit.php script from below link:\n#https://s3-ap-southeast-1.amazonaws.com/qa-americanswan/dump/${ZIPFILE} .\n\nThanks,\nAS Support Team\n\n\n" | mailx -s "Report : Generated by customer_store_credit.php" $MAILRECEIPENTS -aFrom:as-support@intelligrape.com
